# Builds the Windows release package: dist\samaya-windows\ and dist\samaya-windows-<version>.zip.
# It holds the prebuilt apps (static MSVC runtime, so nothing else to install), the page, the
# sample refinery cases, setup.bat and a README.
#
#   powershell -ExecutionPolicy Bypass -File tools\windows\package.ps1 [-SkipBuild]
param([switch]$SkipBuild)
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
if (-not $SkipBuild) {
  & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'build.ps1') -Preset windows-release -Test
  if ($LASTEXITCODE -ne 0) { throw 'Build or tests failed.' }
}
$build = Join-Path $Root 'build\windows-release\apps\studio'
$version = (& (Join-Path $build 'samaya.exe') --version) -replace '^samaya\s+', ''
$dist = Join-Path $Root 'dist\samaya-windows'
Remove-Item -Recurse -Force $dist -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path (Join-Path $dist 'bin'), (Join-Path $dist 'tools\windows') | Out-Null
Copy-Item (Join-Path $build 'samaya.exe'), (Join-Path $build 'samaya-studio.exe') (Join-Path $dist 'bin')
Copy-Item -Recurse (Join-Path $build 'ui') (Join-Path $dist 'bin\ui')
Remove-Item (Join-Path $dist 'bin\ui\mock-result.js') -ErrorAction SilentlyContinue
# Sample cases: generated by cases/mrpl.py (Python), small and medium sizes.
$samples = Join-Path $dist 'bin\samples'
New-Item -ItemType Directory -Force -Path $samples | Out-Null
$tmp = Join-Path $env:TEMP 'samaya-samples'
Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
$mrpl = Join-Path $Root 'cases\mrpl.py'
if (Get-Command py -ErrorAction SilentlyContinue) { & py -3 $mrpl generate --out $tmp | Out-Null }
else { & python $mrpl generate --out $tmp | Out-Null }
if ($LASTEXITCODE -ne 0) { throw 'Could not generate the sample cases (Python 3 is needed).' }
Get-ChildItem $tmp -Filter 'mrpl_*_small.mps' | Copy-Item -Destination $samples
Get-ChildItem $tmp -Filter 'mrpl_*_medium.mps' | Copy-Item -Destination $samples
Copy-Item (Join-Path $Root 'setup.bat') $dist
Copy-Item (Join-Path $Root 'tools\windows\setup.ps1') (Join-Path $dist 'tools\windows')
Copy-Item (Join-Path $Root 'docs\WINDOWS.md') (Join-Path $dist 'README.md')
$zip = Join-Path $Root "dist\samaya-windows-$version.zip"
Remove-Item -Force $zip -ErrorAction SilentlyContinue
Compress-Archive -Path $dist -DestinationPath $zip
Write-Output "package: $dist"
Write-Output "zip: $zip"
